server:
  port: 8082

spring:
  application:
    name: course
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/devdojo?allowPublicKeyRetrieval=true
    username: root
    password: admin

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true
